"""NFHS-6 indicator metadata for Data YT Shorts: short label, topic, direction and hook weight.

dir: +1 higher is better, -1 higher is worse, 0 neutral/contextual.
hook: 3 = everyday topic people argue about (alcohol, obesity, marriage, phones), 2 = clear and relatable,
      1 = technical (vaccine doses, diet sub-groups). Short labels are written to fit on a phone screen.
"""

# id: (label, topic, dir, hook)
META = {
    1: ("Population under 5", "people", 0, 1),
    2: ("Population under 15", "people", 0, 2),
    3: ("Population aged 60+", "people", 0, 3),
    4: ("Homes with electricity", "home", 1, 1),
    5: ("Clean drinking water", "home", 1, 2),
    6: ("Homes using iodised salt", "home", 1, 1),
    7: ("Homes with health insurance", "home", 1, 3),
    8: ("Homes with a bank account", "home", 1, 1),
    9: ("Women & girls who ever went to school", "education", 1, 2),
    10: ("Homes where a woman owns house/land", "women", 1, 3),
    11: ("Kids (2-4) in pre-school", "education", 1, 2),
    12: ("Women with 10+ years of school", "education", 1, 2),
    13: ("Men with 10+ years of school", "education", 1, 2),
    14: ("Women who have used the internet", "digital", 1, 3),
    15: ("Men who have used the internet", "digital", 1, 3),
    16: ("Women married before 18", "marriage", -1, 3),
    17: ("Men married before 21", "marriage", -1, 3),
    18: ("Children per woman (fertility rate)", "people", 0, 3),
    19: ("Teen girls (15-19) already mothers", "marriage", -1, 3),
    20: ("Couples using family planning", "family", 0, 2),
    21: ("Modern family planning use", "family", 0, 1),
    22: ("Traditional family planning use", "family", 0, 1),
    23: ("Women sterilised", "family", 0, 2),
    24: ("Men sterilised", "family", 0, 2),
    25: ("Unmet family-planning need", "family", -1, 1),
    26: ("Unmet need for spacing", "family", -1, 1),
    27: ("Unmet need for limiting", "family", -1, 1),
    28: ("Check-up in first 3 months of pregnancy", "pregnancy", 1, 1),
    29: ("Mothers with any antenatal visit", "pregnancy", 1, 1),
    30: ("Mothers with 4+ antenatal visits", "pregnancy", 1, 1),
    31: ("Protected against neonatal tetanus", "pregnancy", 1, 1),
    32: ("Iron-folic acid 100+ days", "pregnancy", 1, 1),
    33: ("Iron-folic acid 180+ days", "pregnancy", 1, 1),
    34: ("Mother & Child Protection card", "pregnancy", 1, 1),
    35: ("Babies born in hospitals", "birth", 1, 2),
    36: ("Born in government hospitals", "birth", 0, 2),
    37: ("Births with skilled staff", "birth", 1, 1),
    38: ("C-section births", "birth", 0, 3),
    39: ("C-sections in private hospitals", "birth", 0, 3),
    40: ("C-sections in government hospitals", "birth", 0, 2),
    41: ("Mothers checked within 2 days", "birth", 1, 1),
    42: ("Home-born babies checked in 24h", "birth", 1, 1),
    43: ("Babies checked within 2 days", "birth", 1, 1),
    44: ("Children fully vaccinated", "vaccines", 1, 2),
    45: ("Fully vaccinated (card only)", "vaccines", 1, 1),
    46: ("Children with any vaccine", "vaccines", 1, 1),
    47: ("BCG vaccine", "vaccines", 1, 1),
    48: ("Polio (3 doses)", "vaccines", 1, 1),
    49: ("Pentavalent (3 doses)", "vaccines", 1, 1),
    50: ("Measles 1st dose", "vaccines", 1, 1),
    51: ("Measles 2nd dose", "vaccines", 1, 1),
    52: ("Hepatitis B birth dose", "vaccines", 1, 1),
    53: ("Rotavirus (3 doses)", "vaccines", 1, 1),
    54: ("Vitamin A dose", "vaccines", 1, 1),
    55: ("Vaccinated at government centres", "vaccines", 0, 1),
    56: ("Vaccinated at private clinics", "vaccines", 0, 2),
    57: ("Kids with diarrhoea", "child health", -1, 2),
    58: ("Kids with severe diarrhoea", "child health", -1, 1),
    59: ("Kids with respiratory infection", "child health", -1, 1),
    60: ("Sick kids taken to a doctor", "child health", 1, 1),
    61: ("Breastfed within 1 hour of birth", "breastfeeding", 1, 1),
    62: ("Exclusively breastfed (<6 months)", "breastfeeding", 1, 2),
    63: ("Breastfeeding (<6 months)", "breastfeeding", 1, 1),
    64: ("Breastmilk/water only (<6 months)", "breastfeeding", 1, 1),
    65: ("Solids + breastmilk at 6-8 months", "breastfeeding", 1, 1),
    66: ("Adequate diet (breastfed, 6-23m)", "child diet", 1, 1),
    67: ("Adequate diet (not breastfed, 6-23m)", "child diet", 1, 1),
    68: ("Babies (6-23m) with an adequate diet", "child diet", 1, 3),
    69: ("Stunted children", "child nutrition", -1, 3),
    70: ("Wasted children", "child nutrition", -1, 2),
    71: ("Severely wasted children", "child nutrition", -1, 2),
    72: ("Underweight children", "child nutrition", -1, 3),
    73: ("Overweight children", "child nutrition", -1, 3),
    74: ("Underweight women", "body", -1, 2),
    75: ("Underweight men", "body", -1, 2),
    76: ("Overweight/obese women", "body", -1, 3),
    77: ("Overweight/obese men", "body", -1, 3),
    78: ("Women: high blood sugar", "sugar", -1, 1),
    79: ("Women: very high blood sugar", "sugar", -1, 2),
    80: ("Women with high sugar (diabetes risk)", "sugar", -1, 3),
    81: ("Men: high blood sugar", "sugar", -1, 1),
    82: ("Men: very high blood sugar", "sugar", -1, 2),
    83: ("Men with high sugar (diabetes risk)", "sugar", -1, 3),
    84: ("Women: mild high BP", "bp", -1, 1),
    85: ("Women: severe high BP", "bp", -1, 2),
    86: ("Women with high blood pressure", "bp", -1, 3),
    87: ("Men: mild high BP", "bp", -1, 1),
    88: ("Men: severe high BP", "bp", -1, 2),
    89: ("Men with high blood pressure", "bp", -1, 3),
    90: ("Wives in household decisions", "women", 1, 2),
    91: ("Women paid in cash for work", "women", 1, 3),
    92: ("Women with own bank account", "women", 1, 2),
    93: ("Women with own mobile phone", "women", 1, 3),
    94: ("Hygienic period protection (15-24)", "women", 1, 2),
    95: ("Wives facing spousal violence", "violence", -1, 3),
    96: ("Violence during pregnancy", "violence", -1, 2),
    97: ("Sexual violence before 18", "violence", -1, 2),
    98: ("Women who use tobacco", "tobacco", -1, 3),
    99: ("Men who use tobacco", "tobacco", -1, 3),
    100: ("Women who drink alcohol", "alcohol", -1, 3),
    101: ("Men who drink alcohol", "alcohol", -1, 3),
}

# men/women pairs for gender-gap Shorts: (women id, men id, topic phrase)
GENDER_PAIRS = [(12, 13, "10+ years of school"), (14, 15, "internet use"), (74, 75, "underweight"),
                (76, 77, "overweight/obese"), (80, 83, "high blood sugar"), (86, 89, "high blood pressure"),
                (98, 99, "tobacco"), (100, 101, "alcohol"), (16, 17, "child marriage"), (23, 24, "sterilisation")]

# rivalries / neighbours people actually argue about
RIVALS = [("Tamil Nadu", "Kerala"), ("Tamil Nadu", "Karnataka"), ("Tamil Nadu", "Andhra Pradesh"),
          ("Tamil Nadu", "Telangana"), ("Kerala", "Karnataka"), ("Andhra Pradesh", "Telangana"),
          ("Maharashtra", "Gujarat"), ("Maharashtra", "Karnataka"), ("Punjab", "Haryana"),
          ("Uttar Pradesh", "Bihar"), ("Madhya Pradesh", "Chhattisgarh"), ("Bihar", "Jharkhand"),
          ("West Bengal", "Odisha"), ("West Bengal", "Assam"), ("Rajasthan", "Gujarat"),
          ("NCT of Delhi", "Haryana"), ("Himachal Pradesh", "Uttarakhand"), ("Goa", "Kerala"),
          ("Tamil Nadu", "Puducherry"), ("Kerala", "Goa"), ("Uttar Pradesh", "Rajasthan"),
          ("Punjab", "Himachal Pradesh"), ("Assam", "Meghalaya"), ("Mizoram", "Nagaland"),
          ("Tamil Nadu", "Gujarat"), ("Kerala", "Uttar Pradesh"), ("Maharashtra", "Tamil Nadu"),
          ("NCT of Delhi", "Maharashtra"), ("Karnataka", "Telangana"), ("Sikkim", "Arunachal Pradesh")]

SOUTH = ["Tamil Nadu", "Kerala", "Karnataka", "Andhra Pradesh", "Telangana", "Puducherry"]

SHORT_NAME = {"Andaman and Nicobar Islands": "Andaman & Nicobar", "Dadra & Nagar Haveli and Daman & Diu": "DNH & Daman Diu",
              "NCT of Delhi": "Delhi", "Jammu and Kashmir": "J&K"}
