// Generated by scripts/datayt/build_beats.py: every built beat Short, for the Remotion registry.
import clue01 from "../../public/datayt/beats/clue01/data.json";
import cnt01 from "../../public/datayt/beats/cnt01/data.json";
import vs01 from "../../public/datayt/beats/vs01/data.json";
import type {BeatData} from "./BeatStory";

export const BEATS = [clue01, cnt01, vs01] as unknown as BeatData[];
