// Generated by scripts/datayt/build_mapped.py: every built MAPPED Short, for the Remotion registry.
import map01 from "../../public/datayt/mapped/map01/data.json";
import type {MappedData} from "./IndiaMapped";

export const MAPPED = [map01] as unknown as MappedData[];
