// Generated by scripts/datayt/build_story.py: every built story Short, for the Remotion registry.
import brk01 from "../../public/datayt/stories/brk01/data.json";
import chg01 from "../../public/datayt/stories/chg01/data.json";
import face01 from "../../public/datayt/stories/face01/data.json";
import myth01 from "../../public/datayt/stories/myth01/data.json";
import rank01 from "../../public/datayt/stories/rank01/data.json";
import type {StoryData} from "./DataStory";

export const STORIES = [brk01, chg01, face01, myth01, rank01] as unknown as StoryData[];
