# Generate src/vx/CaseEngine.tsx from the shared VoxEngine.tsx (never edited): adds the code-drawn scene types,
# rebrands the furniture to The Moat Files and keeps the disclaimer on screen for the whole video.
import pathlib
src = pathlib.Path("/Volumes/DarwinSSD/MMVideo/src/vx/VoxEngine.tsx").read_text()
out = src
def sub(a, b):
    global out
    assert a in out, a[:60]; out = out.replace(a, b, 1)
sub('import {HDraw, HWrite, sh, RED as HRED} from "../handkit";', 'import {HDraw, HWrite, sh, RED as HRED} from "../handkit";\nimport {CASE_SCENES} from "./scenes/CaseScenes";')
sub('kinetic: Kinetic};', 'kinetic: Kinetic, ...CASE_SCENES};')
sub('<text x={1880} y={62} fontFamily={TYPE} fontSize={24} fill={C.ink} opacity={0.6} textAnchor="end">Moat &amp; Margin · from the filings</text>',
    '<text x={1880} y={62} fontFamily={TYPE} fontSize={24} fill={C.ink} opacity={0.6} textAnchor="end">The Moat Files · Moat &amp; Margin</text>'
    '<text x={1880} y={94} fontFamily={TYPE} fontSize={19} fill={C.ink} opacity={0.6} textAnchor="end">Educational research, not investment advice · not SEBI-registered</text>')
out = out.replace('Moat &amp; Margin · from the filings', 'The Moat Files · Moat &amp; Margin')
out = "// GENERATED by scripts/make_case_engine.py from VoxEngine.tsx. Do not edit by hand.\n" + out
pathlib.Path("/Volumes/DarwinSSD/MMVideo/src/vx/CaseEngine.tsx").write_text(out)
print("CaseEngine.tsx written", len(out))
